---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: k3s-cluster
  namespace: flux-system
spec:
  type: github
  events:
  - "ping"
  - "push"
  secretRef:
    name: github-token
  resources:
  - kind: GitRepository
    name: flux-system
