---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: 8.4.1
      sourceRef:
        kind: HelmRepository
        name: airflow-helm
        namespace: flux-system
      interval: 5m
  values:
    ###################################
    # Airflow - Common Configs
    ###################################
    airflow:
      extraPipPackages:
      - "airflow-exporter==1.4.1"
      - "sqlalchemy<1.4.0"
      - "azure-storage-blob==12.8.0"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    ###################################
    # Airflow - Scheduler Configs
    ###################################
    scheduler:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    ###################################
    # Airflow - WebUI Configs
    ###################################
    web:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    ###################################
    # Airflow - Celery Worker Configs
    ###################################
    workers:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    ###################################
    # Airflow - Flower Configs
    ###################################
    flower:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64

    ###################################
    # Airflow - DAGs Configs
    ###################################
    dags:
      ## configs for the git-sync sidecar (https://github.com/kubernetes/git-sync)
      ##
      gitSync:
        ## if the git-sync sidecar container is enabled
        ##
        enabled: true
        repo: "https://github.com/AnnaGMiguel/airflow-dags.git"

        ## the sub-path (within your repo) where dags are located
        ##
        ## NOTE:
        ## - only dags under this path (within your repo) will be seen by airflow,
        ##   but the full repo will be cloned
        ##
        repoSubPath: "dags"

        ## the git branch to check out
        ##
        branch: main

    ###################################
    # Kubernetes - Ingress Configs
    ###################################
    ingress:
      enabled: true
      web:
        annotations:
          kubernetes.io/ingress.class: "nginx"
        path: ""
        host: "airflow.${SECRET_CLUSTER_DOMAIN}"

     ## configs for the Ingress of the flower Service
      ##
      flower:
        ## annotations for the flower Ingress
        ##
        annotations:
          kubernetes.io/ingress.class: "nginx"
        path: ""
        host: "flower.${SECRET_CLUSTER_DOMAIN}"

    redis:
      master:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
      slave:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64

    ###################################
    # Database - PostgreSQL Chart
    # - https://github.com/helm/charts/tree/master/stable/postgresql
    ###################################
    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: longhorn
        accessModes:
          - ReadWriteOnce
        size: 2Gi

      master:
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
      slave:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
