apiVersion: v1
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
data:
    GF_AUTH_AZUREAD_AUTH_URL: ENC[AES256_GCM,data:QhuDz1edtbKDlDvBUm4lx9He0uOuiWz37947SeH7fxQznIb2hzCFaqbnDPJRFemWT2ua9m2eyGqGH6K1eXddAwTxYiUCt3g04I95e8A6zNCDXt23k0Sf7GasdAu+Y5K760p8Iw8wXuVzBGiM5ubKXoxM0Y1/luDG62PaVg==,iv:VzQkEGjwytJXGYPez0idKLjM4vwJKvvmrWw97b7+7Ak=,tag:mr946ZxK72bhHW4R+CziuA==,type:str]
    GF_AUTH_AZUREAD_CLIENT_ID: ENC[AES256_GCM,data:Wt+B2aMedFYlZuUGNI/GsnAMrrB1xWK+O4NtnKCRASM5OBtneavgyW+RtiMlO8Ue,iv:6fDHLKaOyYLBzXQQqF6B3sLn2eQVac5XIaV4fFrtd3Q=,tag:Lew453NK5t9iwhElNs2DOg==,type:str]
    GF_AUTH_AZUREAD_CLIENT_SECRET: ENC[AES256_GCM,data:nimtK8Fu2bf8eYHeMyiBzGCHYBANoHcpwusXlZYQEXDZyUoxEbFYqVl8sS5rJlReKbn4WzmfPcVE1cm/3vExnfgaGiOhrr+IBTrGV9meeQ9JNTQIy+i3yFW/86A4XnCTZW5BibDAZUYaxMlXRNNpaXd5K6pbuG/8Jxa2qq9K/43f6OvQgRaiVFBurRTaGPf/L5kn4s2aVeUhXFyW8HHTGQ==,iv:Y67VuXrFhR/th+/SzcxsG68JaZA50b7iBD99K4hgg+w=,tag:W/LG9oUEHOxs6j6o5zkvaQ==,type:str]
    GF_AUTH_AZUREAD_TOKEN_URL: ENC[AES256_GCM,data:KXAzJ99tzeP9ClndtkCuZm+E+iSbQIKFVdCMfrJNiCQcAZvDEVLxuFYjywBIWuf6fl6o3AuydzjOfLmOxn1QpgV6vjKa9NjCWQWmnhV5T4kOE6ZAaLYFE3HMKGgvSzBxvEh4UQrvWxIrSCOWyOg9U2gw1+hpIyj8,iv:FkFEFKZGj0hdFQrP4ZFhGJ8H7arsjmQ5Uq35wV7SOA0=,tag:AsJyVbHYtmZYYc8Q+quSDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-ec4fba156758404d.vault.azure.net
          name: sops-key
          version: c5e21dac9a264cb9b54d106db3c3f980
          created_at: "2021-04-27T20:16:48Z"
          enc: QI2DmMN3vAbxBU2er2RqjVtd4QFeft-v_llztXChQHo8TI4mzwtpBMfHjtiXHky6jb_W7yrJQ7WwxMGWJXHYXgG0gLEumIeS9nHdSqJziNSGFK7XWKxMlxy8ATow8p2i8WRbRBMcC_CkrVBk6DQO_8srx6OIHkpvkdptn2ipb_Y83KVExXgaoXPkc6KEHSUon32QurWaoFsHVKf6XOMT5LXMvcxtL_x1_eDGibVLvMfaXAtvFf2BHd-bWcJHYfK_GES_Xr0SmpLX24WY1MNiKOoHh5ZV0n43UF-hWzNtImpiWci2K0NrwZSn6EBiBZTIs50_9_uNRATEOv0UPjdX1Q
    hc_vault: []
    age: []
    lastmodified: "2021-04-27T20:16:48Z"
    mac: ENC[AES256_GCM,data:Lh1QxbOP5i+90jkz6+N+tqirSPKJGsjSKc6ZIs4o0lp0ygnB9R5AAyRbenQqbGkQ6OdW5rdj3EoeNz8ti5wD4YubCHg/DtoV1SoHCuvuai6WSzMej0uL1og0HneZwN02ymLemJ1ogRe1rqrRd0KwqkmA4ewAM6HLkN74gHG0kFw=,iv:4KJ9YC5s/HXIgpiqADCoos8QHiDoOeQxcsH8czTbEV4=,tag:pnjeVlav5jsqw1r9NlSHxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
