---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dozzle
subjects:
- kind: ServiceAccount
  name: dozzle
  namespace: monitoring
