---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: luander.ribeiro@outlook.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: luander.ribeiro@outlook.com
          apiKeySecretRef:
            name: cloudflare-token
            key: cloudflare-token
