---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "home"
  name: "home-assistant-config-v1"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
