---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.7.4
    env:
      TZ: "Europe/Amsterdam"
    # envFrom:
    # - secretRef:
    #     name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "hass.${SECRET_CLUSTER_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "hass.${SECRET_CLUSTER_DOMAIN}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.10.2
        git:
          deployKeySecret: code-server
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
          - host: "hass-config.${SECRET_CLUSTER_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "hass-config.${SECRET_CLUSTER_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
    prometheus:
      serviceMonitor:
        enabled: true
