---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.cilium.io/
      chart: cilium
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  values:
    encryption:
      # -- Enable transparent network encryption.
      enabled: true

      # -- Encryption method. Can be either ipsec or wireguard.
      type: wireguard

      # -- Enable encryption for pure node to node traffic.
      # This option is only effective when encryption.type is set to ipsec.
      nodeEncryption: true

      wireguard:
        # -- Enables the fallback to the user-space implementation.
        userspaceFallback: false

    operator:
      # -- Enable the cilium-operator component (required).
      enabled: true

      # -- Number of replicas to run for the cilium-operator deployment
      replicas: 1

