apiVersion: v1
data:
    postgres-password: ENC[AES256_GCM,data:uqw5JRccWE9I6pU+4eQzq1a00vWXxQmgV1lUY6ns+stXw8AchYBoj/Wpz9o=,iv:6IqVGBkKu+/KhKEuV3oGRN1LsRzlsPvbkcGbogdbaxM=,tag:DnEfeh5SA6N9R6Z9NNxy9w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: joplin-db
    namespace: joplin
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-ec4fba156758404d.vault.azure.net
          name: sops-key
          version: 1f0762a5e1c5491bac78d22ed00545ac
          created_at: "2022-05-04T06:12:20Z"
          enc: GvsBmtdRRfPsnhHtZnVVk-AJk2WmsM08kPLJzq2UAR7xxS9ZM5HWtHvaL26TBcjY-FesixPOXlmXk6wWifMPxu4lvFhbGyyiwBxExTD1jrlfRM70ZcKroA49pX5mtoLyzDCtJzJbRROHcyxjrE8h1ae_hHJWyPRnfwPYZo98dGiMZi8b6cD4qbyLp8jZJgLjUsJqItG_vVj0LP7HsDxxbHurcZdOTEPyhQ1CoBzHBnU30VDkzfFvfmtjU-WOjQQofWF611WVpg5ibC5o5Nzky9lEEGBgbV0I2YCI5aa6tvZX_RoHBH772xrWsjIBuDMfydsNi6ya9BZiV_gZQj3bUi070jjEOu-HfPrRrhA6U_QZKR0zIWbf7xy9bz85X5LVZlS7nQn2Qtdj4Wh3bO4PCEQ_43eUozyoYNT3T0qyYXrp5w_YQnT19notOkG-uq_yrA5GRLaTV5q7Q_GmWD0BIeKCtjk_DeTe7TqOp1fV1WNl37r_kz6KFUJCNXH28d4KKDmFaiiPXakq_vuEmkVDNV0tac8n2LrBWW8GPu1x8LWioN1ziDt9LXylJ2_KT5RPO0hbNAUKC0PqJKSjis1HVFjVKXYgDZHgOipYq-SeVDgExJl_I5UukIZhEjTB3eowvfImfrwVicR44AoLUdqaGMHf6tu4kcWu3bBbeyHKvFk
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T06:12:21Z"
    mac: ENC[AES256_GCM,data:VzB/ZaDMBc1DV8DWhLP53xOjZjtcLs5wJYTP5GK3m6gaPxy4PlSh8+uWRXUwa4FyhtmomT37B8XqQvp0yzuJfu55i3BlYfM4+2e0kxOjExZdaoVXb9CbAmfwI2qa29VqInykf/g0ruQukdi8p+b++LxxrpOQECpfCa3qW8q9IM0=,iv:OBuoBiD134qtFBReK2ETAsvw9Bpw3Y0H7R/9/Mq/HHs=,tag:awDtTDEeSadM6YprjnAFjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
