---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: falco-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://falcosecurity.github.io/charts
      chart: falco-exporter
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: falco-security-charts
        namespace: flux-system
      interval: 5m
  values:
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
      namespace: falco-system
    tolerations:
    - effect: NoSchedule
      operator: Exists
