---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1

    env:
      SIGNUPS_ALLOWED: true
      DOMAIN: "https://bitwarden.${SECRET_CLUSTER_DOMAIN}"
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
      SENDS_ALLOWED: true
      DISABLE_ADMIN_TOKEN: false
      SMTP_HOST: "${BITWARDEN_SMTP_HOST}"
      SMTP_FROM: "${BITWARDEN_SMTP_FROM}"
      SMTP_FROM_NAME: "Bitwarden"
      SMTP_SECURITY: starttls
      SMTP_PORT: 587
      SMTP_USERNAME: username
      SMTP_PASSWORD: password
      SMTP_TIMEOUT: 15
      YUBICO_CLIENT_ID: "${BITWARDEN_YUBIKEY_CLIENT_ID}"
      YUBICO_SECRET_KEY: "${BITWARDEN_YUBIKEY_SECRET_KEY}"

    envFrom:
    - secretRef:
        name: bitwardensmtp

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        ## Use existing Persistent Volume Claim
        existingClaim: "bitwarden-bitwardenrs-0"

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - host: "bitwarden.${SECRET_CLUSTER_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "bitwarden.${SECRET_CLUSTER_DOMAIN}"

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
