---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emby
  namespace: media
spec:
  ingressClassName: nginx
  rules:
    - host: "emby.${SECRET_CLUSTER_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emby
                port:
                  number: 80