---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.29.2.6364-6d72b0cf6
    env:
      TZ: "${TIMEZONE}"
      PLEX_PREFERENCE_7: "TreatWanIpAsLocal=1"
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
      supplementalGroups:
      - 568
      - 44
      - 106
      - 100
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "10.0.0.193"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "plex.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # autoscaling:
    #   enabled: true
    #   target: plex
    #   minReplicas: 1
    #   maxReplicas: 5
    #   targetCPUUtilizationPercentage: 80
    #   targetMemoryUtilizationPercentage: 80
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        mountPath: "/media"
        type: pvc
        existingClaim: media
        readOnly: true
      backup:
        enabled: false
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 10000Mi
