apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:Bb7UJxtSCbygBKYtO1MKUg==,iv:8odLJSVu5bN/B500C4MVBSfFEf8zbjvTPc+By7YqOJI=,tag:CWtBzLXjBD0X9xeIA1WA9w==,type:str]
    SECRET_SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:RHe91zSpAiRJyUCe3RlLT/H122xuq11zqj0IieYj7HydcRN3S5T3/Yvt55MTxKtkT2TTkpNGussb1Y6o/GBzMB9Ssz3V3RfEHZce4CFJcd7+,iv:wkR/rpGMQaVCOLYAOA1CblmPQmDt75/LH2a4N7IFK1I=,tag:0WHkZU5QCIG/XLLfyK2nYg==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:Th9k/e6NnR0DI/1BooRtLbY5aaSby4znMbUIFQ9O0JGO3zEB,iv:PMbJlmY7aGhh/NNX4zjgmnhgyK4l9y+E8Uwktna6FE0=,tag:WUfT6V5ruwQ6kvEUCxQX4g==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:R19GHb9rT6Ru7Qm1DO7Dq97ibeYyA1IlzI5JjfZmPGGR3A==,iv:E2iDxl0xXQVp7bMIa0G6SmpicI/4pm8GUx1iiurLhSY=,tag:/EuP991EoxuYPP9T3Q444A==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:n1flT1Sg9aTkkKVjFsuRCGw8ZFUwQg1c+lKhei0+QmdpFGD7LTKHyIDtPBo=,iv:V9AGT9e5YWgfOjH66IBsPAaqbHuVdrBZbiq0/0/pOtA=,tag:Tp19bacdXoYQJmK9Er8jBA==,type:str]
    OAUTH2_PROXY_AZURE_TENANT: ENC[AES256_GCM,data:vR9Jm+ieZWAf3fGGo4QzVjro1p9WhpU8usXQVG9MJVs/repW,iv:akQRoP/uMMRjwmklkdVJ8iyLobEQqId6B9ztTzDZjU8=,tag:o/UZnd6rNr2/Axz67nELzQ==,type:str]
    OAUTH2_PROXY_RESTRICTED_ACCESS: ENC[AES256_GCM,data:H/w3N1rqY32ezJx4XtN8JOvDNB/vpQha1RLK64eN4P3giEmyjTgIDU9vvt61IlHgjycsAogP2ayJthkSOjNmain1zA==,iv:LyZMwQglNm5ZDxjzXf8HR/J5lGZm8nWmb1tDfhMcMzw=,tag:iAK/sw2X5Qsb2DpqXKzXgQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:NCvUoHvPi5Jt9QVlCZ3tlgBGbWy/ZATr9oYa,iv:TCgFVRceSawfuImFJ1xG3+KOSlbRcSa7ez0pwVJaN8k=,tag:NwQpSdYn+LgCeZCX7eOxqg==,type:str]
    BITWARDEN_SMTP_HOST: ENC[AES256_GCM,data:fu/zheCS2qbdbwPPe4w=,iv:CYRgiQ2y4Z7XTnA5rNV17tL851Lh4gYaPHZtHwcdDeE=,tag:Z2ldu7155Tg/d8aT89fTlw==,type:str]
    BITWARDEN_SMTP_FROM: ENC[AES256_GCM,data:DQ8kiW6PCmlnTmDgqGs67xyIIA==,iv:8gCnhTWad/Cf6DvDBkKdMWT5u+G1qHom2oxMebPl6SU=,tag:KDlwSgHW2Orzlp6c6ESfBg==,type:str]
    BITWARDEN_YUBIKEY_CLIENT_ID: ENC[AES256_GCM,data:JbHq9bk=,iv:bf6O+FTiOXH3hcnOJ4YGhw1ASEmOoaalYzpUKupcZMM=,tag:8Hi3FkcWGUfy8hoJukmZ5g==,type:int]
    BITWARDEN_YUBIKEY_SECRET_KEY: ENC[AES256_GCM,data:/hCXnr9GzI4pIFtuQKD2KducNkTWZDpuMeHobA==,iv:rDdH+SkIgObgIcYzxZgQSwTSb51QXLr0EwwQa+m+de4=,tag:eEmHYgLcZZ+3YPNaeWDAPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-ec4fba156758404d.vault.azure.net
          name: sops-key
          version: 1f0762a5e1c5491bac78d22ed00545ac
          created_at: "2021-07-15T10:16:54Z"
          enc: hW2IU-6xPSlc-OdrRXUNwY3vBg0BhA8XPZTMCxOOQ2WLb-2YMCuxrPl6RKqLeadZOD6drH3UG4U4TJmXVR1D-zGy8VVrbHVUVMYEdDPwrPS_pVbeqcq3bxCL142Icy_ksrcLrjEKmda8iNudrAbQjsR1m2MtsYO7_5eNDAIYs8DI11CazVskz229B6XoPcBiCv6RO1BD1wPRNcrkCiv4QQ8RPn2WaXzmdOZMW1r7TZPqU6rdkLI6dVqv_gi_RBI-aBQx3C_bM9rYFPit4xipasbEvaHn4Fv3_F43VUHWyJeDdrpsvYyLz0zHMVoklaQMPuTcRjyUwLAKvFTiqGelHPrsuFakbZVxhjsGHoihjsNq2ATjurmDXTHnCBOKersW-zyRyJ7lV1-NiyNxi91ZgYChpAaUIFYRZrlyo97qWZ1bbZt1YEQ_oh9_XT80jpELX5kT0fqXRUOEEGXE1lLaISKS2-y-U1Urva2bn3qNM71pmM2_Py36jeNp8WE45pwLIycOtPAizPKOeIIXW54oGRZVZ7k0e2e2Vykla20i_yp-GHkKSVxgcyS5oGvUWkTfS3349o_VB2M3AvxdLVTzc-ieLabFWdrHhy1NCTe7yHJl8SwXQVYT4W5E8fhLo1Cdai5Zq3E9Jfq0tWKu5mm_yBub5nTwpY1XGcm6rcu7fGE
    hc_vault: []
    age: []
    lastmodified: "2021-07-15T10:16:54Z"
    mac: ENC[AES256_GCM,data:1YQx3AgU8pQqNEaJU7i6bXEKI+o53gO278u1CqHpPAQzto5DoUr46GBHEFhBr1zPg/37O1qTDwjyT252u8MshCppoIFA1pCd6t5/WBpXWyU+DmAfPhRxZilBNa8Bj1Aj/LOZpp+81r9VpPRSgneuW+Ys7g8baFfkrVjDtgKvNkA=,iv:O5fkKusKRK9ScF+78AfbEcgrPzYZjz5TXeWAjTqc4Fs=,tag:sOlyCxW+2TtjT0JE4xWPbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
