---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: qbittorrent
  namespace: media
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: qbittorrent
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
