---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/home-operations/qbittorrent-libtorrentv1
      tag: 5.1.4@sha256:f8ded91789511af07db8e47bcfde9440f3c2d235e85b7eee13c9d03a7a4107c9
    env:
      TZ: "Europe/Amsterdam"
      QBT_WEBUI_PORT: &port 80
      QBT_TORRENTING_PORT: &torrentPort 31288
      QBITTORRENT__BitTorrent__Session__SavePath: /downloads
      QBITTORRENT__BitTorrent__Session__TempPath: /downloads/incomplete
    probes:
      liveness:
        enabled: true
        spec:
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/v2/app/version
            port: *port
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      startup:
        enabled: true
        spec:
          failureThreshold: 30
          periodSeconds: 10
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities: { drop: ["ALL"] }
    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        ports:
          bittorrent:
            enabled: true
            port: *torrentPort
            protocol: TCP
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 568
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        type: pvc
        existingClaim: media
        mountPath: /downloads
        subPath: downloads/qbittorrent
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 2048Mi
