---
apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprisesearch
spec:
  version: 7.15.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring
  config:
    ent_search.external_url: https://localhost:3002
