---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: "datadog-secret"
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog-api-key

