---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.datadoghq.com
      chart: datadog
      version: 3.59.6
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
      interval: 5m
  values:
    targetSystem: "linux"
    datadog:
      apiKeyExistingSecret: datadog-secret
      appKeyExistingSecret: datadog-secret
      clusterName: home
      site: "datadoghq.eu"
      tags: []
      logs:
        enabled: true
        containerCollectAll: false
        containerCollectUsingFiles: true
      apm:
        portEnabled: true
        socketPath: /var/run/datadog/apm.socket
        hostSocketPath: /var/run/datadog/
      processAgent:
        enabled: true
        processCollection: false
      systemProbe:
        enableTCPQueueLength: false
        enableOOMKill: false
        collectDNSStats: false
