---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr
      pullPolicy: IfNotPresent
      tag: 4.0.9.2244

    strategy:
      type: Recreate

    env: 
      TZ: "Europe/Amsterdam"
      PUID: 1000
      PGID: 1000

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "sonarr.${SECRET_CLUSTER_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_CLUSTER_DOMAIN}"
    probes:
      liveness:
        enabled: true
        ## Set this to true if you wish to specify your own livenessProbe
        custom: true
        ## The spec field contains the values for the default livenessProbe.
        ## If you selected custom: true, this field holds the definition of the livenessProbe.
        spec:
          exec:
            command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10

    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
      supplementalGroups:
      - 568
      - 100
    persistence:
      config:
        enabled: true
        type: pvc
        size: "25Gi"
        storageClass: longhorn
      media:
        enabled: true
        mountPath: "/media"
        type: pvc
        existingClaim: media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
