apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-poller-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: "unifi-poller-secret"
    creationPolicy: Owner
  data:
    - secretKey: UP_UNIFI_DEFAULT_PASS
      remoteRef:
        key: unifi-poller-secret
