---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/unpoller/unpoller
      tag: v2.11.2
    env:
      tz: "europe/amsterdam"
      UP_UNIFI_DEFAULT_ROLE: "homelab-controller"
      UP_UNIFI_DEFAULT_URL: "https://10.0.8.1"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "unifipoller"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"
    envfrom:
    - secretref:
        name: unifi-poller-password
    prometheus:
      servicemonitor:
        enabled: true
    affinity:
      nodeaffinity:
        requiredduringschedulingignoredduringexecution:
          nodeselectorterms:
            - matchexpressions:
              - key: beta.kubernetes.io/arch
                operator: in
                values:
                  - amd64
    service:
      main:
        ports:
          http:
            port: 9130
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 5s
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi

