---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: k3s-cluster
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
  - kind: HelmRelease
    namespace: 'cert-manager'
    name: '*'
  - kind: HelmRelease
    namespace: 'bitwarden'
    name: '*'
  - kind: HelmRelease
    namespace: 'kube-system'
    name: '*'
  - kind: HelmRelease
    namespace: 'longhorn-system'
    name: '*'
  - kind: HelmRelease
    namespace: 'media'
    name: '*'
  - kind: HelmRelease
    namespace: 'metrics'
    name: '*'
  - kind: HelmRelease
    namespace: 'networking'
    name: '*'
  - kind: HelmRelease
    namespace: 'airflow'
    name: '*'
  - kind: HelmRelease
    namespace: 'app-dashboard'
    name: '*'
  suspend: false
