---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://external-secrets.github.io/kubernetes-external-secrets/
      chart: kubernetes-external-secrets
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-external-secrets-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: external-secrets
    fullnameOverride: external-secrets
    env:
      POLLER_INTERVAL_MILLISECONDS: 100000
    envVarsFromSecret:
      AZURE_TENANT_ID:
        secretKeyRef: azkv-credentials
        key: tenant_id
      AZURE_CLIENT_ID:
        secretKeyRef: azkv-credentials
        key: client_id
      AZURE_CLIENT_SECRET:
        secretKeyRef: azkv-credentials
        key: client_secret
    serviceMonitor:
      enabled: true
