---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: v7.1.1-arm64
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - arm64

    # Oauth client configuration specifics
    config:
      # Create a new secret with the following command
      # openssl rand -base64 32 | head -c 32 | base64
      # Use an existing secret for OAuth2 credentials (see secret.yaml for required fields)
      # kubectl create secret generic oauth2-azure \
      # --from-literal client-id=value \
      # --from-literal client-secret=value \
      # --from-literal cookie-secret=value
      # --namespace security
      # Example:
      existingSecret: oauth2-azure
      google: {}
        # adminEmail: xxxx
        # serviceAccountJson: xxxx
        # Alternatively, use an existing secret (see google-secret.yaml for required fields)
        # Example:
        # existingSecret: google-secret
      # Default configuration, to be overridden
      configFile: |-
        provider = "azure"
        azure_tenant = "5da12343-3348-4c6e-b62a-5526ff29978c"
        email_domains = [ "luander.net", "outlook.com" ]
      # Custom configuration file: oauth2_proxy.cfg
      # configFile: |-
      #   pass_basic_auth = false
      #   pass_access_token = true
      # Use an existing config map (see configmap.yaml for required fields)
      # Example:
      # existingConfig: config
    # To authorize individual email addresses
    # That is part of extraArgs but since this needs special treatment we need to do a separate section
    authenticatedEmailsFile:
      enabled: true
      # template is the name of the configmap what contains the email user list but has been configured without this chart.
      # It's a simpler way to maintain only one configmap (user list) instead changing it for each oauth2-proxy service.
      # Be aware the value name in the extern config map in data needs to be named to "restricted_user_access".
      template: ""
      # One email per line
      # example:
      restricted_access: |-
        iam@luander.net
        luander.ribeiro@outlook.com
        annagmiguel@outlook.com
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
