apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unifi-poller-password
  namespace: metrics
spec:
  backendType: azureKeyVault
  keyVaultName: nskfbe4xjyb8yar8eixt8ha9
  data:
    - key: unifi-poller-secret
      name: UP_UNIFI_DEFAULT_PASS