---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission-openvpn
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bananaspliff.github.io/geek-charts
      chart: transmission-openvpn
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: geek-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    image:
      repository: "haugene/transmission-openvpn"
      tag: "3.6"
      pullPolicy: "IfNotPresent"
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
    env:
      - name: OPENVPN_PROVIDER
        value: "NORDVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
      - name: OPENVPN_USERNAME
        valueFrom: # Reference to the secret | openvpn.username
          secretKeyRef:
            name: "openvpn"
            key: "username"
      - name: OPENVPN_PASSWORD
        valueFrom: # Reference to the secret | openvpn.password
          secretKeyRef:
            name: "openvpn"
            key: "password"
      - name: NORDVPN_PROTOCOL
        value: "TCP"
      - name: NORDVPN_COUNTRY
        value: "ES" # Country where we want to download over VPN
      - name: NORDVPN_CATEGORY
        value: "P2P" # VPN Type
      - name: LOCAL_NETWORK
        value: "192.168.0.0/24"
      - name: TRANSMISSION_PEER_PORT
        value: "47444"
      - name: TRANSMISSION_DOWNLOAD_DIR
        value: "/downloads/transmission"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - "transmission.${SECRET_CLUSTER_DOMAIN}"

    volumes:
      - name: "media-data"
        persistentVolumeClaim:
          claimName: "video-media" # PersistentVolumeClaim created earlier
      - name: "dev-tun" # Needed for VPN
        hostPath:
          path: "/dev/net/tun"
    volumeMounts:
      - name: "media-data"
        mountPath: "/data"
        subPath: "configs/transmission-data" # Path /mnt/ssd/media/configs/transmission-data where transmission writes the configuration
      - name: "media-data"
        mountPath: "/downloads/transmission"
        subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where transmission downloads Torrents
      - name: "dev-tun"
        mountPath: "/dev/net/tun" # Needed for VPN
    securityContext:
      capabilities: # Needed for VPN
        add:
          - NET_ADMIN
    # Security context for pod
    # Can be used to allow ipv6 for openvpn, because
    # some VPN providers push an ipv6 route with will fail without
    # ipv6 support, see https://github.com/haugene/docker-transmission-openvpn/issues/789
    # Note that your kubelet needs to allow changing this sysctl setting, see
    # https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls
    #
    # - podSecurityContext:
    #     sysctls:
    #       - name: net.ipv6.conf.all.disable_ipv6
    #         value: "0"
    podSecurityContext: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
  
