---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app transmission
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: *app
      version: 8.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      custom-webui:
        name: custom-webui
        image: curlimages/curl:7.76.1
        command:
        - "/bin/sh"
        - "-c"
        - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          runAsUser: 568
          runAsGroup: 568

    env:
      TZ: "Europe/Amsterdam"
      TRANSMISSION_WEB_HOME: /config/flood-for-transmission/

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 100
      - 1000

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_CLUSTER_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_CLUSTER_DOMAIN}/oauth2/start"
        hosts:
        - host: &host "transmission.${SECRET_CLUSTER_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host

    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        cpu: 1000m
        memory: 250Mi

    persistence:
      config:
        enabled: true
        mountPath: /config
        type: pvc
        size: "5Gi"
        storageClass: "longhorn"
      downloads:
        enabled: true
        mountPath: /downloads
        subPath: "downloads/transmission"
        type: pvc
        existingClaim: media 
