---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: cloudflare-real-ip
  namespace: networking
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
  clientIPDetection:
    # Use CF-Connecting-IP exclusively for Cloudflare
    customHeader:
      name: "CF-Connecting-IP"
      failClosed: false
  tcpKeepalive:
    idleTime: 60s
    interval: 30s
    probes: 5
  timeout:
    http:
      requestReceivedTimeout: 0s
      idleTimeout: 4h
      streamIdleTimeout: 0s
  tls:
    minVersion: "1.2"
    maxVersion: "1.3"
