---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: global-config
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
  routing:
    host:
      maxBodySize: 104857600 # 100MB
  security:
    tls:
      minVersion: VersionTLS12
      maxVersion: VersionTLS13
