---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: global-config
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
                  topologyKey: kubernetes.io/hostname
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
  telemetry:
    metrics:
      prometheus: {}
