---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddnsrs
  namespace: networking
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 65532 # corresponds to tag 'nonroot' user
            runAsGroup: 65532
            fsGroup: 65532 # ensures /tmp is mounted with permissions to 'nonroot' user
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          containers:
          - name: ddnspy
            image: ghcr.io/luander/ddnsrs:main@sha256:f6c900fd560edb9b14ff9b78fc2905f08f8b5790d9cbb9e9d7ba3bbb0033a2da
            imagePullPolicy: IfNotPresent
            args: [ "home.luander.net" ]
            env:
            - name: TMPDIR
              value: "/tmp"
            - name: RUST_LOG
              value: "debug"
            envFrom:
            - secretRef:
                name: cloudflare-api
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          volumes:
          - name: tmp-volume
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: [ "ReadWriteOnce" ]
                  storageClassName: "longhorn"
                  resources:
                    requests:
                      storage: 1Mi
          restartPolicy: OnFailure
