---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddnsrs
  namespace: networking
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          containers:
          - name: ddnspy
            image: ghcr.io/luander/ddnsrs:main@sha256:1e22576083f884a19c8f45eb462607e798fd59dd2b2406e418b4c3a81aa3a72f
            imagePullPolicy: IfNotPresent
            args: [ "home.luander.net" ]
            envFrom:
            - secretRef:
                name: cloudflare-api
            securityContext:
              runAsUser: 65532 # corresponds to tag 'nonroot' user
              runAsGroup: 65532
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - all
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
