---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: "cloudflare-api"
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: cloudflare-dns-edit

