---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddnsrs-cronjob-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Mi
