---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hackmd
  namespace: hackmd
spec:
  releaseName: hackmd
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: hackmd
    version: 2.0.0
  values:
    # Default values for hackmd.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    replicaCount: 1

    deploymentStrategy: RollingUpdate

    image:
      repository: hackmdio/hackmd
      tag: 2.2.0-cjk
      pullPolicy: IfNotPresent

    service:
      name: hackmd
      type: ClusterIP
      port: 3000

    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - hackmd.kube.luander.net
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
       cpu: 500m
       memory: 512Mi
      requests:
       cpu: 100m
       memory: 128Mi

    persistence:
      enabled: true
      ## hackmd data Persistent Volume access modes
      ## Must match those of existing PV or dynamic provisioner
      ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
      ##
      accessModes:
        - ReadWriteOnce
      annotations: {}
      existingClaim: ""
      size: 2Gi
      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"

    podAnnotations: {}

    extraVars: []

    nodeSelector: {}

    tolerations: []

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64

    ## Configuration values for the postgresql dependency.
    ## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
    ##
    postgresql:
      install: true
      image:
        tag: "9.6"
      postgresqlUsername: "hackmd"
      postgresqlDatabase: "hackmd"
      ## Default: random 10 character string
      # postgresqlPassword:
      master:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      slave:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64