---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.25.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values: 
    controller:
      ingressClass: nginx
      extraEnvs: 
      - name: TZ
        value: Europe/Amsterdam
      replicaCount: 2

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
