---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  type: github
  address: https://github.com/luander/k3s-cluster
  secretRef:
    name: github-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: github
  namespace: flux-system
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    namespace: 'cert-manager'
    name: '*'
  - kind: HelmRelease
    namespace: 'bitwarden'
    name: '*'
  - kind: HelmRelease
    namespace: 'kube-system'
    name: '*'
  - kind: HelmRelease
    namespace: 'longhorn-system'
    name: '*'
  - kind: HelmRelease
    namespace: 'media'
    name: '*'
  - kind: HelmRelease
    namespace: 'monitoring'
    name: '*'
  - kind: HelmRelease
    namespace: 'networking'
    name: '*'
  - kind: HelmRelease
    namespace: 'airflow'
    name: '*'
  - kind: HelmRelease
    namespace: 'app-dashboard'
    name: '*'
  suspend: false
