apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
data:
    token: ENC[AES256_GCM,data:MmaKrYcns4SpsJKyeT/vKCZ4VCc3fB/dCWZYZtJUBGKojkWhQCG7Rw==,iv:FYO0ZlMvqghT7KTDyy+mfRPUiIGVTaw1+mxqLwxdbLA=,tag:jy/KBjt98H5cxwKDtolXTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-ec4fba156758404d.vault.azure.net
          name: sops-key
          version: c5e21dac9a264cb9b54d106db3c3f980
          created_at: "2021-04-27T17:43:11Z"
          enc: DEujRfPJseXMJvt3HFppVE331PchD6PZo4DlvxFZmRn2NUj4F7aCaeoWRgbArmGwFy93Nuy3dsESedAGtxc9p8c3mncfL6nbE1RZiMGezfNYrWazuKXozCuBJLGuUo8c8PTpMN1jzKlepqVKdSJBK9stzF7dT30pf2Yetyn8gt-2TweNh1MntKaAKDxDfeJMG9vl573VIbhnimJwpDFAfDKW4QqKvLH5d8ICQjDZD09NTOcVh9-KyZWtj1zvyl4JTfDYJTCgPmE1dG6MBaVECZHG1c6-PutOFxQUsrdfbPoGc9BmssDe7YkBX97-HVC8_BsPoRl4O-QzpUhoABbFXQ
    hc_vault: []
    age: []
    lastmodified: "2021-04-27T17:43:12Z"
    mac: ENC[AES256_GCM,data:T/NXphVzKbf2cA/38nV04EvGSZWyHWjnrBCN7m3Nz+ht/8qIMSDltcsYWQAm8hXUxqfz8rZkNkQt+K16TIQInHn26Kkt7e9GLq20D10sWTa6oeUfMRVr4fC1N/4j6YrX5rhdje9eIOqVmwa77P1wS2c0DUVen8Etm8Oo/4ZwEWo=,iv:tMsPKGNUFd/R0dij3k2zxrqaAJVC4Yp+3/5Q0oRh1OQ=,tag:EdGo2YHxij4WsNrTIh9qFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
