apiVersion: v1
data:
    token: ENC[AES256_GCM,data:08ZjjNWEb5V0VEWLUo54uqZsBfKqNNS176xWl59/VOJMpDetsg24Rc4foPheUDUwBfcJDXYmcPE=,iv:0QV5KOOE8z2lZY3XELTYmY/xa8l/4Ft1NZCBedkLzR8=,tag:8V0mUGpJqCcSP/HNhSpjRQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-notification-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-ec4fba156758404d.vault.azure.net
          name: sops-key
          version: 1f0762a5e1c5491bac78d22ed00545ac
          created_at: "2021-07-15T10:18:32Z"
          enc: wQhp0AkDZBNb_Fi6KynIuYuroOyRJhp6TJasK52Q1O4VWOYK9qm3D9Yw-WrxYXyg_fEGNuleLdMvu9B8ee-SMMKR-2BzGtE568rZBkNYPFVYDT112BxIqhzpN_rh20eFMqaa2YnW84RGOH3Z2idXGFF91T8dwy1tXfAwXsXq68jZ-PubyhFXGIwvjNoqTXn918LiGsxbyBrxVjkejMeSeJ8EnTMGyhoy3DO5ZA21Jkr3F3Z0xzsHMNheTzukzWo1nBmArpS7Iu5gzU5cy_2Dskl_YeuSb7zqcStJrZf3ukLJ8_RiBLBS6smOOxQ0N7O4nxZLnhOCR_IuUE4r-OjmA1YFEO40QlfZcxUiBkKCKrYA_EM7rkcFUhwR-BCdYpNtg4aEEzEtHz34wP638SmqcKIh1i3g0wy24ht9rvr6X-JzX-AmOp7qem42as0LoKRZpdZUPbIaP7nBH_0JT_UT5trXc-st9rvBCdyQwkFEVWjeTfcsCS403naeBb4XXcfTF7KylG04K1Pqvl43WaO5fO1lvWy34Z4hs2vFShF07_gYduw9SxPRLZWeBfX0v54RaQMhikmTy9GtkALaAbpX8u4u_PQ-2IlwpgcfsnuYvU3jPFuuCDa_0CeuCMH8hLbyup5FV8zd2ULfIIEkg7yQnuX5XR6Bc8Z4RkLnvyamp6g
    hc_vault: []
    age: []
    lastmodified: "2021-07-15T10:18:32Z"
    mac: ENC[AES256_GCM,data:eiKd3976SbRcC+FyIDiHXpfG89/CwaaJ9HoomBdgrQm6SZ5uP9Pzw/xOo1d4MxGkg2hsXaSEaUrWXljAWOdtrs+a4mAT7c+BCwPik9IaZj4VwWI46gvs9gan07q3jbs8YLsT868CUYJ5PoA+NspT6MZUGXXr5Bvnn+3ET3ipNIg=,iv:MhANroY+4K+tX+4cejZve6DzB9ocPgrbmJS4KtUDm8A=,tag:qad3CHBRA4YShs8bAUAAEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
