all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: luander
    k3s_release_version: v1.32.3+k3s1

    k3s_state: installed
    k3s_become: true
    k3s_server:
      disable:
        - traefik
      # Stop k3s control plane having workloads scheduled on them
      node-taint:
        - "node-role.kubernetes.io/controlplane=true:NoSchedule"

    # Manifests to install in K3s
    k3s_server_manifests_templates:
      - secrets.yaml.j2

k3s_cluster:
  hosts:
    control:
      ansible_host: 10.0.8.10
      k3s_control_node: true
    node1:
      ansible_host: 10.0.8.11
    node2:
      ansible_host: 10.0.8.12
    node3:
      ansible_host: 10.0.8.13
    node4:
      ansible_host: 10.0.8.14
