---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.external-secrets.io
      chart: external-secrets
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: false
    podSecurityContext:
      fsGroup: 2000

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 500m
        memory: 512Mi

