---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      tenantId: "5da12343-3348-4c6e-b62a-5526ff29978c"
      vaultUrl: "https://nskfbe4xjyb8yar8eixt8ha9.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azkv-credentials
          key: AZURE_CLIENT_ID
          namespace: kube-system
        clientSecret:
          name: azkv-credentials
          key: AZURE_CLIENT_SECRET
          namespace: kube-system
