---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: "cloudflare-token"
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: cert-manager-cloudflare-token

