---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: actions-runner-controller-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://summerwind.github.io/actions-runner-controller/
  timeout: 3m
