apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-external-secret.yaml
- postgres-configmap.yaml
- postgres-helm-release.yaml
- helm-release.yaml
- ml-helm-release.yaml
- redis-helm-release.yaml
- httproute.yaml
- nfs-volumes.yaml
