---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photo-library-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "nas.luander.net"
    path: "/volume1/photo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photo-library-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: immich-photo-library-pv
