---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - name: yamllint
      uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1
      with:
        yamllint_flags: "-c .github/yamllint.config.yaml ./cluster"
