---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: yamllint
      uses: reviewdog/action-yamllint@290d92c84b22627946efc7fd6f038ade2d2beede # v1
      with:
        yamllint_flags: "-c .github/yamllint.config.yaml ./cluster"
