---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: yamllint
      uses: reviewdog/action-yamllint@5dd4640db975e4cac6f4e775a401695bafc28068 # v1
      with:
        yamllint_flags: "-c .github/yamllint.config.yaml ./cluster"
